### PR TITLE
Upgrade to Freeciv 2.6.0-beta1 and performances improvement

### PR DESCRIPTION
**Pull request by javaxubuntu**
Hello,
The changes since I forked your repository are :
## Upgrade to freeciv-2.6.0-beta1
Add all nations and all tilespec (the tilespec are packaged in the APK but only amplio2 and hexemplio are available via the game menus).
Cheating AI and civ2civ3 and experimental ruleset are now available.
Freeciv is now integrated as a dependency instead of being part of the source code. A script downloads is automatically and patches it.
Android-specific files from the data folder are moved to userdata, and data is now a symlink to the unpacked Freeciv source code.

## Python UI improvements
Add techtree that displays like the desktop GTK version.
New Pick Nation dialog that makes easier to filter nations: lib/freeciv/nationdlg.py
City dialog: add pollution and plague labels
Show unit's home city
Make "add to city" button work (for settler and migrants)
Graphics from tilesets are no longer upscaled and therefore look better. They are now displayed as is, unless specialists buttons on city dialog that are now bigger. Also, font size is adapted to the device DPI. Map view can still be scaled by zoom feature or city dialog.
Fix back button that needed 2 press if the goto action was used before.
Fix a memory leak acf1953ab1cc2d0c1e1fe8b0f6599ef5ccf5ff69
Library upgrades (see below) also fixes some memory leaks and display problems when switching between apps.
Fix a lagging issue b3b29d606499b6a366ed4a21b314dce992af5ecf
Fix city label's font color to be more visible: it's now black if background is bright, as of desktop version

## Library upgrades
Upgrade SDL to version 2.0.4, and SDL2_image and SDL2_ttf. (alpha blending modifications are now done via SDL_modify_blending.patch)
Upgrade Python to version 2.7.2 and disable app.fork feature because there is a random deadlock issue with os.fork 45947443d5d9f43910fb00a254132180a983b20d 8fff4e9ed0959595a3e6cdf84440b3d6991a97e1 The server is now a standalone executable.
Python and SDL are now downloaded using python-for-android instead of git submodules.
Add Curl because it's now required to compile Freeciv.

## Other
Fix some build problems 064c925373a64f96828d9d085f27d41e7b9e9e5a f0922b84ba319074df17bb95ff83ce040aa6a3f9 f36d88345849bb34421930835fb08644b7827cf2
Created src/log_custom_format.c to view all messages from Freeciv C code or python code on the same file
Removed unuseful files, for example data/civrc-2.3-default and freeciv.rc
Removed scrips that are no longer used, for example data/flags/compose.sh, gentechtree.py and pyclient_always.h
Renamed src/configure to genMakefile.sh because it's not generated with autoconf.

Please note that I disabled error reporting, and I didn't change anything about app version.
Best regards.

### CODE REVIEW

**Comment by zielmicha** [comment]
Great :) I will review the changes in about a week and release new version then.

**Comment by javaxubuntu** [comment]
You'll make a beta release first?

**Comment by zielmicha** [comment]
The changes look good, I have given you write access to the repo, so you can push to it directly.

I see you have removed instructions for building SDL2, SDL_image and SDL_ttf. Have you changed anything about them?

**Comment by javaxubuntu** [comment]
SDL build instructions are now in the root Makefile, but I can move them to android/Makefile.
SDL is dowloaded by this command:
p4a symlink_dist --dist-name freeciv-android-jni-dependancies --android_api 17 --ndk_ver r12b --output pythonforandroid

**Pull request merged**
